[betfair]
username = "alex.baigneres@gmail.com "
password = "75bilan1E_"
app_key = "xxk6GuNHefdoslw5"
# Copy the entire content of client-2048.crt below
cert_file = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCfxdgnYqkTD7fq
FpatLvSwPxVkVnaWbDvWX2F0byHZWZCTxScV1xM5xYrcaUQo12FAVPARsMTu7+9V
SjRauZ/XdUYEtV9fG9xUSqmSyO3EQWNS7JPy4BKDrJhYpvYMk57YBwB9D5pEXVrE
azfJ7QnTexaG9ypzCFG1/MhGWgL0Z89xwzGFB1HJzDYqGdILcr3WsBv7sQ3bt0IY
N7EQdbLLFhpSd/19zx9rbKXbnkqHXtsSonGSC74ztsdN+BUkbSdQ5McQ1gSF6+Ic
YZ7ZrL9FPBksa939NWuh/iuOCkkTZb6faKOLweq/v4dVuF0eXdESosc1MuNfWexA
U0BAkpejAgMBAAECggEAA1y2KqFNwPE6Q9iiMgdc3yuob8K/caJSf8wR6v7Nz7km
XcWynlUY2ExwqZHok7Dat3esddtP5seIBybqEk35kcR+px5cFdXfBQXl5wkl375F
dGSB+ipgXSDe92AH1sYmIYMtJjhXTfVXT+62nFwzQUOePp9PI6rL6hm4Nl99efTp
PeNh1ppJwRi/83+Ck+u7FEqCnqU2NQoCDv68O5BZy5+hysnhvDrL0xo+29lF1HKT
ZRxDDTjgUOfSiiPgHMxbBhyoT1NMOplUEiK58Wvy3qHQwMx4rTzQVnuXAiHBEawL
YcC8XTYLh0reoh6Q+/xuJ0qIV9E1bVS5pW1plR876QKBgQDRWiwnk630Ut57u0pd
BFFK5nuDqwrBKyeBAJymyrut05yKeRy00yvC9ATqn2rvZrGxhE6q06gMjz6+O68E
8S+BtsKxgLZfM4JiYx+qUfHUU4BxeGNlqFjXfyFOOWAyTnVj4GEeDg2IThGtE6y9
EMITXHc1/QAEYbTl42Z52DyBHQKBgQDDX5LPLbg1UdzcNBmHlj7dfpSO7a0/7BuF
/HSEyNhO2b/9ZkN1kT1ggORQvqvVDzIqTVhuOvrKsuOmCp6Z0gnvFrQgVRzg7VE1
4OYtBTYm7LbNDYzrMJAG13UbVndrYRhBCVLMYJKgi1SttbU5cQFL1SmX4XxEn+Ld
R1Dehu7fvwKBgBmbPetZVN2dhTj9H4thC9BtgI4KTbZy4NIWkRKVmX8Zcvw89BXp
/mBKGI/aD+pYVUOxOy4J1XQz0SjThATGu1jSUd4EMEpUso32MdlTTJD75an7X6z/
el5hXmGDAxEkJ5efykEy1tTlN6RD080MT7CujqY729StXsL/nXkpybzBAoGAJYkE
HJetD1ll9ExyJzF/bHB4PCl/ootLEmfZPvWTUTrWfumZxkmcICFDPBwVyT49JhFs
Dul361+JCwp5RBYtYGjdPGT9wlz1wEMwFbAtojbSO/0BeOIAmb/lONZY5SFnVn9j
D+7x3LRIFYOWiK2kURxn/E0O4eRR4q9j4wzLceMCgYBCw+JxSAf/VjXlVxlt4lVK
lPItvrn0hqH8KhuNUs927p+PvCQZKsXW5udAXziTzSWFVETrhmj0wfrCZgh6YFYo
fOAh95whoIXPkGaQ2IR2OoNi1+IOqa1mijPeK4RMklbFCqfZ43THKbvAFl54f50A
gCtD7p0Rwr2LotIHTP4zbw==
-----END PRIVATE KEY-----"""
# Copy the entire content of client-2048.key below
key_file = """-----BEGIN CERTIFICATE REQUEST-----
MIICiDCCAXACAQAwQzELMAkGA1UEBhMCR0IxDzANBgNVBAcMBkxvbmRvbjEOMAwG
A1UECgwFTXlCb3QxEzARBgNVBAMMCkJldGZhaXJCb3QwggEiMA0GCSqGSIb3DQEB
AQUAA4IBDwAwggEKAoIBAQCfxdgnYqkTD7fqFpatLvSwPxVkVnaWbDvWX2F0byHZ
WZCTxScV1xM5xYrcaUQo12FAVPARsMTu7+9VSjRauZ/XdUYEtV9fG9xUSqmSyO3E
QWNS7JPy4BKDrJhYpvYMk57YBwB9D5pEXVrEazfJ7QnTexaG9ypzCFG1/MhGWgL0
Z89xwzGFB1HJzDYqGdILcr3WsBv7sQ3bt0IYN7EQdbLLFhpSd/19zx9rbKXbnkqH
XtsSonGSC74ztsdN+BUkbSdQ5McQ1gSF6+IcYZ7ZrL9FPBksa939NWuh/iuOCkkT
Zb6faKOLweq/v4dVuF0eXdESosc1MuNfWexAU0BAkpejAgMBAAGgADANBgkqhkiG
9w0BAQsFAAOCAQEAi9lxYm8PMly7WitBAHbpmsSD/nL0DEkA4/aenT9fq+Fzkncl
9KnFTIMMSuw8I7zm+eHdcQPSbi69cS+F0rcNjzdgh5UpnaA2t5Q+vEn+1GlXe2Wj
cmSo1GOYWwOCZXC1ahAMlcVoTpY7iIxXzMCNPKgJOmv5NWpKa0IHkwPOIvNtlhoZ
6sJ4S+ZTWgUwWKStnl4qEvQAQjNgrCCevq7Sr+EjN/OmzlgnV7zaSExUPeWGzouO
Foz8bvHL8t+MiyvLV17U0RTRy9rGROoj5TXk+CDFHbN79IAwZChbIods1QVQy7Ve
3yXgjLnaIueZxSl3B4Z589m0e6NuChK19iS72Q==
-----END CERTIFICATE REQUEST-----"""
